### ISSUE TITLE
 error in unique validation

### ISSUE THREAD

**Issue by ARCHAMO** [blakehaswell/mongoose-unique-validator#90] opened 2018-10-30 13:11 UTC
I have a table that is empty, one of its fields (consecutive) has a restriction of unique but at the time of consuming the service to save a record tells me that the consecutive is already used. What is the personalized message

Modelo
![image](https://user-images.githubusercontent.com/12633358/47720037-f3a90180-dc1a-11e8-8ce5-6b7e0d820aa5.png)

Controller
![image](https://user-images.githubusercontent.com/12633358/47720109-1affce80-dc1b-11e8-84b4-48580fe790bb.png)

packaje.json
![image](https://user-images.githubusercontent.com/12633358/47720153-3d91e780-dc1b-11e8-83d3-f4d91bebaee3.png)

**Comment by viveleroi** [comment] 2018-10-30 23:43
Duplicate of #88 

Unfortunately we aren't sure how to fix it yet, Mongoose changed internal logic.

**Closed by viveleroi** 2018-10-30 23:43 UTC
