### ISSUE TITLE
The error response contains the _id field.

### ISSUE THREAD

**Issue by NoMercy235** [blakehaswell/mongoose-unique-validator#94] opened 2019-01-04 16:18 UTC
Hello! In your example:
```javascript
var mongoose = require('mongoose');
var uniqueValidator = require('mongoose-unique-validator');

// Define your schema as normal.
var userSchema = mongoose.Schema({
    username: { type: String, required: true, unique: true },
    email: { type: String, index: true, unique: true, required: true },
    password: { type: String, required: true }
});
```
You say that the error generated looks like this:
```javascript
{
    message: 'Validation failed',
    name: 'ValidationError',
    errors: {
        username: {
            message: 'Error, expected `username` to be unique. Value: `JohnSmith`',
            name: 'ValidatorError',
            kind: 'unique',
            path: 'username',
            value: 'JohnSmith'
        }
    }
}
```

I have a similar schema, but the error response also contains information about the `_id` field - which I don't want.

```javascript
{
    "errors": {
        "email": {
            "message": "email must be unique",
            "name": "ValidatorError",
            "properties": {
                "type": "unique",
                "message": "{PATH} must be unique",
                "path": "email",
                "value": "admin@tta.com",
                "reason": {}
            },
            "kind": "unique",
            "path": "email",
            "value": "admin@tta.com",
            "reason": {},
            "$isValidatorError": true
        },
        "_id": {
            "message": "_id must be unique",
            "name": "ValidatorError",
            "properties": {
                "type": "unique",
                "message": "{PATH} must be unique",
                "path": "_id",
                "value": "5c2f860d05bd337d1d8c97f9",
                "reason": {}
            },
            "kind": "unique",
            "path": "_id",
            "value": "5c2f860d05bd337d1d8c97f9",
            "reason": {},
            "$isValidatorError": true
        }
    },
    "_message": "User validation failed",
    "message": "User validation failed: email: email must be unique, _id: _id must be unique",
    "name": "ValidationError"
}
```

I don't understand how the `_id` can fail to be unique since that is always guaranteed by mongo. I don't send anything weird as input data. Only the email and the password. Could you assist me with this issue please?

Here is my schema:

```javascript
const schema = new mongoose.Schema({
    email: { type: String, required: true, unique: 'Email must be unique: ({VALUE})' },
    password: { type: String, required: true },
});

schema.plugin(uniqueValidator, { message: '{PATH} must be unique' });
```

You can see that the `email` field uses the `'Email must be unique: ({VALUE})'` option, but the `_id` uses the `'{PATH} must be unique'` option.

**Comment by viveleroi** [comment] 2019-01-04 16:54
The validator will only query for an _id if the _id field was already provided and it's not an update. https://github.com/blakehaswell/mongoose-unique-validator/blob/master/index.js#L86

Because we build a validator for each unique index, that gets executed during mongoose's validation phase. There's nothing extra we're doing.

I would recommend throwing some debug/console statements in there to see what the incoming `_id` and `isNew` values are, and maybe see which record it thinks is the "duplicate".

The message itself is configured when we build the validator. In your example it's using the "plugin options" one because there is no "index options" one.

**Comment by NoMercy235** [comment] 2019-01-04 17:06
I see. This is what the model looks like before calling the `.save()` method.

```javascript
model {
  '$__':
   InternalCache {
     strictMode: true,
     selected: undefined,
     shardval: undefined,
     saveError: undefined,
     validationError: undefined,
     adhocPaths: undefined,
     removing: undefined,
     inserting: undefined,
     version: undefined,
     getters: {},
     _id: ObjectID { _bsontype: 'ObjectID', id: [Buffer] },
     populate: undefined,
     populated: undefined,
     wasPopulated: false,
     scope: undefined,
     activePaths:
      StateMachine { paths: [Object], states: [Object], stateNames: [Array] },
     pathsToScopes: {},
     ownerDocument: undefined,
     fullPath: undefined,
     emitter:
      EventEmitter { _events: {}, _eventsCount: 0, _maxListeners: 0 },
     '$options': true },
  isNew: true,
  errors: undefined,
  _doc:
   { firstName: '',
     lastName: '',
     isAdmin: false,
     isActive: true,
     _id: ObjectID { _bsontype: 'ObjectID', id: [Buffer] },
     password: '123456',
     email: 'admin@tta.com' } }
```

There is indeed a value on `_id`, but that's not provided by me. I assume it's created by mongo when the document is instantiated. There is also the `isNew` property which is set to `true`, so I would think that should be enough to know it's not an update, but a create action.

**Comment by viveleroi** [comment] 2019-01-04 17:14
I wasn't aware that an _id was created client-side before save, otherwise this would have been an issue for a long time now. Before you call `save`, you haven't communicated with mongo itself, so maybe this is something mongoose or another plugin is doing?

Not only is the `_id` field populated here, but there has to be a matching record already in the db. Can you dump out what's in the `Buffer` and then see what it matches up to?

**Comment by NoMercy235** [comment] 2019-01-04 17:20
The Buffer there holds this value: `5c2f9587368fbb20e18ac244`. However, that doesn't match with anything I have in the database (there are only 4 users). Besides, each subsequent request changes the buffer values. It seems to increment it by one - e.g. the next one was `5c2f95d3368fbb20e18ac245`.

**Comment by markus-heinisch** [comment] 2019-01-17 15:22
I have the same problem. Switching back to 2.0.1 solves my problem storing new document. :-(

**Comment by viveleroi** [comment] 2019-04-17 19:02
This is a duplicate of #88

**Closed by viveleroi** 2019-04-17 19:02 UTC
