### ISSUE TITLE
is it possible to not apply the uniqueness on other documents and only on array-subdocuments???

### ISSUE THREAD

**Issue by Stathismi** [blakehaswell/mongoose-unique-validator#89] opened 2018-10-12 17:25 UTC
For example, is it possible to have unique:true on schema , use the plugin to check for array-subdocuments uniqueness but search only on the array not on other documents. Because I want the unique values to be allowed on other documents too or collections and only be unique on the array! thanks

**Comment by viveleroi** [comment] 2018-10-12 19:56
Not currently. Duplicate of #36

**Closed by viveleroi** 2018-10-12 19:56 UTC
